{
  "openapi": "3.0.1",
  "info": {
    "title": "默认模块",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [],
  "paths": {
    "/mxn/collect/apply": {
      "post": {
        "summary": "MXN Collection Application",
        "deprecated": false,
        "description": "代收申请\n\nappId需使用墨西哥比索对应的，用户支付成功后增加墨西哥比索余额",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "appId": {
                    "type": "integer",
                    "description": "Business ID (obtained from the backend, must correspond to the currency in the URL)"
                  },
                  "orderId": {
                    "type": "string",
                    "description": "Merchant Order Number",
                    "maxLength": 48
                  },
                  "name": {
                    "type": "string",
                    "description": "Payer's Name (format: English letters, spaces allowed, 1–30 characters, \"firstName middleName lastName\"; middleName optional; special characters allowed: '.-)",
                    "minLength": 1,
                    "maxLength": 30,
                    "pattern": "^[A-Za-z\\s'.\\-]+$"
                  },
                  "phone": {
                    "type": "string",
                    "description": "Valid phone number"
                  },
                  "email": {
                    "type": "string",
                    "description": "Valid email address",
                    "format": "email"
                  },
                  "amount": {
                    "type": "string",
                    "description": "Transaction Amount (unit: Mex$, precise to two decimal places; do not use punctuation such as \",\")",
                    "pattern": "^\\d+\\.\\d{2}$"
                  },
                  "payType": {
                    "type": "string",
                    "description": "Payment Method: QR (Barcode Payment) or VA (Virtual Account)",
                    "enum": [
                      "QR",
                      "VA"
                    ]
                  },
                  "inBankCode": {
                    "type": "string",
                    "description": "Collection Code. When payType is QR, inBankCode supports: OXXO, CASH payment methods; when payType is VA, inBankCode is CLABE"
                  },
                  "callBackUrl": {
                    "type": "string",
                    "description": "Redirect URL after successful payment",
                    "format": "uri"
                  },
                  "callBackFailUrl": {
                    "type": "string",
                    "description": "Redirect URL after failed payment",
                    "format": "uri"
                  },
                  "notifyUrl": {
                    "type": "string",
                    "description": "Callback URL",
                    "format": "uri"
                  },
                  "subject": {
                    "type": "string",
                    "description": "Payment Note (transaction title, product name, payment reason)"
                  },
                  "body": {
                    "type": "string",
                    "description": "Additional Details"
                  },
                  "partnerUserId": {
                    "type": "string",
                    "description": "Unique User Identifier (e.g., userId), used for risk control. Must be valid; otherwise, the transaction may be affected. Allowed format: numbers, letters, or common symbols -~!@#$%&*()_.",
                    "pattern": "^[A-Za-z0-9\\-~!@#$%&*()_]+$"
                  },
                  "sign": {
                    "type": "string",
                    "description": "Signature"
                  }
                },
                "required": [
                  "appId",
                  "orderId",
                  "name",
                  "phone",
                  "email",
                  "amount",
                  "payType",
                  "inBankCode",
                  "callBackUrl",
                  "callBackFailUrl",
                  "partnerUserId",
                  "sign"
                ]
              },
              "examples": {
                "1": {
                  "value": {
                    "amount": "20.00",
                    "callBackFailUrl": "https://www.example.com/failed",
                    "payType": "QR",
                    "callBackUrl": "https://www.example.com/success",
                    "inBankCode": "CASH",
                    "orderId": "SINGLE_1763358741905",
                    "phone": "1234567890",
                    "appId": "4755",
                    "name": "TEST NAME",
                    "partnerUserId": "dfff@fg43123",
                    "sign": "Si8+iTS7zZ4oX1bMCZ9PPFoJwgw9mGEwMc1UIADOrbs7xlCL+f5e+OYcvhKa4HXCxybqu6MTft6t6Smy9gvu8bPw/erwHdKbP/QzRDU5qHfMj9+1IZzZvJQJR/i5/TW9Y+L4xkOOsaTXfEYuDsZTjyNqy/si5EbUgl1CzVMuH3BORpB7H2f0P34RHqt8t5SZet7YfZLs+dcriczmqHAKhILHgIc7VHSfiAna00J2KjM93qO6kXa8LIjw7FVbX5f6ZMOUjrl13M3DDx01qSW0JVCSxRqEN9yTYTPMV8eFCSk+Picr78/vyMEKnRjnccUx4OZy1cK/9rIfi538xTEAbQ==",
                    "email": "test.single@example.com"
                  },
                  "summary": "QR支付"
                },
                "2": {
                  "value": {
                    "appId": "4755",
                    "orderId": "VA_1763358741905",
                    "payType": "VA",
                    "inBankCode": "CLABE",
                    "amount": "43.43",
                    "name": "Sofía López Martínez",
                    "email": "test@example.com",
                    "callBackUrl": "https://www.example.com/success",
                    "callBackFailUrl": "https://www.example.com/failed",
                    "partnerUserId": "dfff@fg43123",
                    "sign": "hYNVZTSCTWeR8X0HfhQ2zxoCTeM5ilX8tElAaNbfGDNzjpklR6r/LQZQ/IEO6SQvAc7EdKnAObcBhOxoUvQbeUNy1o8xcp4TV8ZX32McBPbAB/fu+lPF2SbtahoFs3W5w4Gg3ZMa9nLsStP6m1qER7rfaBOBDmGjUIbwDXUaXYwhLKVepB4N9dmE/r9/kch3SKXkFD/2NlT7HgN4CSWKTr04dd7awgYZm6PFlL9U3F0ZvgCEJouNBezNu2fuVz1ylgPtsXTKn2xLgCekrvwG+9WmQPnQzUC5kVlyLGpKvyVK9EMgHHTfg/12Lu1fyxcqLY8Zm/RAU55lAs/kxLQvpQ=="
                  },
                  "summary": "VA支付示例"
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "1: Normal, 0: Exception"
                    },
                    "error": {
                      "type": "string",
                      "description": "Error code"
                    },
                    "msg": {
                      "type": "string",
                      "description": "Error description"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "orderId": {
                          "type": "string",
                          "description": "Merchant Order Number (must be unique)"
                        },
                        "orderNo": {
                          "type": "string",
                          "description": "Platform Order Number"
                        },
                        "payUrl": {
                          "type": "string",
                          "description": "Payment URL (QR returns barcode payment URL, VA returns CLABE virtual account payment URL)"
                        },
                        "bankCode": {
                          "type": "string",
                          "description": "Channel Code (QR returns barcode, VA returns CLABE)"
                        },
                        "qrCode": {
                          "type": "string",
                          "description": "Barcode, returns the barcode number (only returned for QR payment)"
                        },
                        "bankNo": {
                          "type": "string",
                          "description": "CLABE Virtual Account Number (only returned for VA payment)"
                        },
                        "bankUserName": {
                          "type": "string",
                          "description": "Account Name (only returned for VA payment)"
                        },
                        "sign": {
                          "type": "string",
                          "description": "Signature"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "1": {
                    "summary": "QR支付",
                    "value": {
                      "status": "1",
                      "error": "00000000",
                      "msg": "",
                      "data": {
                        "orderId": "SINGLE_1763358111905",
                        "orderNo": "2025111713522220822",
                        "payUrl": "https://www.paycashglobal.com/formato.php?referencia=MTQ3MTMyNDEwMjQzNQ==&interno=1",
                        "bankCode": "CASH",
                        "qrCode": "1471324102431",
                        "sign": "mpcB0wfbvGpCSNbT8Gs+D4Tt1eMDqTgnuY6yVUAdemccC07nnWrxSPk4srHFXeoXpdWm+CKFh89rghU16kZq2pm9dw0jSlns0dj5c7sDO8Te0KMNGfleuQ+N/16sGZr/LE7MAWj6Z902ymiff6q+N1ljTfIDypHTztbGDpJvemZ9OkB2BCemsoAX6ukkXyZJPI+gkyJEDCPfOcWfXeNmdWOKxyXLOJEjIBno2oyZoDs3yJqkMtCyQW1cjgTTOQbnxgCjHV9YQ+OcLVdkFroC/HrP8p9c8qRICDX/NMEt4Z0Zo1eBV07rkebuY60+A1kSuD7axO0UxSq6BbXKjgNqyQ=="
                      }
                    }
                  },
                  "2": {
                    "summary": "VA支付",
                    "value": {
                      "status": "1",
                      "error": "00000000",
                      "msg": "",
                      "data": {
                        "orderId": "VA_1763358741905",
                        "orderNo": "2025111713522220823",
                        "payUrl": "https://checkout-mx.fusionpay.net?checkout=MjAyNTExMTQxMTAyNTIzNjM0OSZHVjE5ODkxNjY5MzI0MzEwNzczNzYmNjg0MTgwMjkyMDE5ODQ0MDAw",
                        "bankCode": "CLABE",
                        "bankNo": "684180292019844000",
                        "bankUserName": "Sofía López Martínez",
                        "sign": "QwXUII9P895b0008Avsep0OqxuxuQai56vAP1ks1saVJnT/hIWiE9rM4i5uI1CQ0yGNGVkVV25evO+7MssalgWqQNr0tTE0RHCJ6nK0baNz680CHp4IFxLp5TV4OLlNpLfyTNxiYLu4TzsFQuOAsDyTzOH6LnBBLC+syn1S8r4OkkcxrjDnonPc6E4wPZyJouiXe7+cxvSWxl+QSn8dXudxBVddhhTbiwJb2+ATZTDDMmeD7BlU9e8x8IKlR9j7l9Xa4hGU/GRvBqNAIhHXiQVldIlOP1I5L9Ez78kty8dyB2+YIgm5q2gRyl+XotAlOjq8cWti4dau1B7gi3bfqtw=="
                      }
                    }
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/mxn/collect/query": {
      "post": {
        "summary": "MXN Collection Query",
        "deprecated": false,
        "description": "查询代收订单\n异步通知后，通过orderNo查询二次确认状态",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "appId": {
                    "type": "integer",
                    "description": "Business ID (obtained from the backend, must correspond to the currency in the URL)"
                  },
                  "orderId": {
                    "type": "string",
                    "description": "Merchant Order Number"
                  },
                  "orderNo": {
                    "type": "string",
                    "description": "Platform Order Number (faster response)"
                  },
                  "sign": {
                    "type": "string",
                    "description": "Signature"
                  }
                },
                "required": [
                  "appId",
                  "orderId",
                  "sign"
                ]
              },
              "example": {
                "appId": 1054,
                "orderId": "M22222000028",
                "sign": "EmyJGm3ELzG4FsOc0Krs9ncbSjo4oTGuXWML+7djYla3+VAwa9wS17z38p/7U2ZAjroO04XrE7YXcB1o76Dtyipj3h3bJzs7FYma1QNkMUdt9hh7m8U6hMsMQX7vIWHtXNwz4pbTSC75+kQWXaCew7KoE6LXECdJU8AISgNgeki2TK9R0pCfshr0Z2SZBPeuT6OvIH5LdmqgdZhuqnffGU2qnXk4KMkO848e6/WALLBR+LE1wyKHfPnYVcuKSMVYxkvKyyIL5JIPEgW0o5bh4RCbaUn3NZtyYwrU1uQ3ZDFRThm9j6XAQP+LBlmq3nOePqBtp/VDVarRaV+7FbQg3A=="
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "1: Normal, 0: Exception"
                    },
                    "error": {
                      "type": "string",
                      "description": "Error code"
                    },
                    "msg": {
                      "type": "string",
                      "description": "Error description"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "orderId": {
                          "type": "string",
                          "description": "Merchant Order Number (must be unique)"
                        },
                        "orderNo": {
                          "type": "string",
                          "description": "Platform Order Number"
                        },
                        "amount": {
                          "type": "string",
                          "description": "Transaction Amount"
                        },
                        "actualAmount": {
                          "type": "string",
                          "description": "Received Amount"
                        },
                        "fee": {
                          "type": "string",
                          "description": "Transaction Fee"
                        },
                        "status": {
                          "type": "integer",
                          "description": "Order Status (0 Not Started, 1 Processing, 2 Success (final), 3 Failed (final), -1 Exception Pending Confirmation)",
                          "enum": [
                            -1,
                            0,
                            1,
                            2,
                            3
                          ]
                        },
                        "payTime": {
                          "type": "string",
                          "description": "Payment Success Time (available when status=2) (Mexico Time), format: yyyy-MM-dd HH:mm:ss",
                          "pattern": "^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}$"
                        },
                        "errorMsg": {
                          "type": "string",
                          "description": "Payment Failure Reason (available when status=3)"
                        },
                        "sign": {
                          "type": "string",
                          "description": "Signature"
                        }
                      }
                    }
                  }
                },
                "example": {
                  "status": "1",
                  "error": "00000000",
                  "msg": "",
                  "data": {
                    "orderId": "M22222000028",
                    "orderNo": "6023042811314347",
                    "amount": "50000.00",
                    "actualAmount": "0.00",
                    "fee": "0.00",
                    "status": 1,
                    "sign": "fP433ygWVDLVGxYkVnGJj7riGq0U3vyVX+MbBAImxfGLZkZcEAHVEoVYuULZSmXAAXKRSyd67WlDNm+24pougM54ofAoH4HMtCL2tfCoBReFyz3z02AGKkrKE2xWhSpWoqfQoBvzwuN5iGMMu0s9Q1YvqiwJ8WDVIENnmiIyD8qDJN7caHTW2US14/faG+69AvnuIgJ/nu7/jogOlgEYdZdVYU7gcRDE+d47KjlFGswQkJ/h/uzV7cWtUqrtOO7ZnZ3/z33Xx8awokX36QoYcPSWAU0h+Ij9O9402HNhm1eTbYcLU0uI/z8xCAtyAI/tTyiFijpiNlxUKQj+zKsILw=="
                  }
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/mxn/pay/apply": {
      "post": {
        "summary": "MXN Disbursement Application",
        "deprecated": false,
        "description": "创建代付订单\n\n说明：appId 墨西哥比索， amount 墨西哥比索，实收结算墨西哥比索",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "appId": {
                    "type": "integer",
                    "description": "Business ID (obtained from the backend, must correspond to the currency in the URL)"
                  },
                  "orderId": {
                    "type": "string",
                    "description": "Merchant Order Number",
                    "maxLength": 48
                  },
                  "amount": {
                    "type": "string",
                    "description": "Transaction Amount (unit: Mex$, precise to two decimal places; do not use punctuation such as \",\")",
                    "pattern": "^\\d+\\.\\d{2}$"
                  },
                  "accountType": {
                    "type": "string",
                    "description": "Account Type: BANK_CARD (Debit Card (16 digits)), BANK_ACCOUNT (CLABE (18 digits))",
                    "enum": [
                      "BANK_CARD",
                      "BANK_ACCOUNT"
                    ]
                  },
                  "bankCode": {
                    "type": "string",
                    "description": "Bank Code. For specific values, see [Complete Bank Code List](/en/docs/api/version2/Mexico_BankCodes.md)"
                  },
                  "accountNo": {
                    "type": "string",
                    "description": "User Bank Account Number"
                  },
                  "name": {
                    "type": "string",
                    "description": "Recipient Name (format: English letters, spaces allowed, 1-30 characters, \"firstName middleName lastName\" (middleName optional, special characters '.- supported))",
                    "minLength": 1,
                    "maxLength": 30,
                    "pattern": "^[A-Za-z\\s'\\.-]+$"
                  },
                  "phone": {
                    "type": "string",
                    "description": "Valid phone number"
                  },
                  "email": {
                    "type": "string",
                    "description": "Valid email address",
                    "format": "email"
                  },
                  "notifyUrl": {
                    "type": "string",
                    "description": "Callback URL",
                    "format": "uri"
                  },
                  "subject": {
                    "type": "string",
                    "description": "Payment Note (transaction title, product name, payment reason)"
                  },
                  "body": {
                    "type": "string",
                    "description": "Additional Details"
                  },
                  "partnerUserId": {
                    "type": "string",
                    "description": "Unique User Identifier (e.g., userId), used for risk control. Must be valid; otherwise, the transaction may be affected. Allowed format: numbers, letters, or common symbols -~!@#$%&*()_.",
                    "pattern": "^[A-Za-z0-9\\-~!@#$%&*()_]+$"
                  },
                  "sign": {
                    "type": "string",
                    "description": "Signature"
                  }
                },
                "required": [
                  "appId",
                  "orderId",
                  "amount",
                  "accountType",
                  "bankCode",
                  "accountNo",
                  "name",
                  "email",
                  "partnerUserId",
                  "sign"
                ],
                "additionalProperties": false
              },
              "example": {
                "appId": 1054,
                "orderId": "M100000450012",
                "amount": "55.00",
                "accountType": "BANK_ACCOUNT",
                "bankCode": "STP",
                "accountNo": "99418029201a844099",
                "name": "John Doe",
                "email": "johndoe@example.com",
                "subject": "Payment for services",
                "body": "Payment description",
                "partnerUserId": "73744645@f233",
                "sign": "I1PeK3eJEVsFFNowxVRqMXpeWa1lr/BcRpBi8SsW4wVo1+5AC1JsrFq/m/L3214NzKHvtDWi4zia3DL3dPut0yMyUyqL91LNCSaeISbGsQPlhEsQpyTOryS/RKOfsrn2Xo37SCF/phAvndOk2jwwGwqM5xLz1ms9Ukl85wv27QFNrXIMxK2p181e7MpMYrgf+xvEBE/VqCtKMtN9pO449wWwXzHWNPbZ76s4pAvKwRE9yXQDr7Iw14Dktcnl1FoLM4gWM/obkO+mz6SyAGDuXhVh/+OD/IGNiCyTCNq6ciQY28UnCFV6ZIP40gxsFhfBJKbK+Raw7y1Bh912ifYfug=="
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "1: Normal, 0: Exception"
                    },
                    "error": {
                      "type": "string",
                      "description": "Error code"
                    },
                    "msg": {
                      "type": "string",
                      "description": "Error description"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "orderId": {
                          "type": "string",
                          "description": "Merchant Order Number (must be unique)"
                        },
                        "orderNo": {
                          "type": "string",
                          "description": "Platform Order Number"
                        },
                        "sign": {
                          "type": "string",
                          "description": "Signature"
                        }
                      }
                    }
                  }
                },
                "example": {
                  "status": "1",
                  "error": "00000000",
                  "msg": "",
                  "data": {
                    "orderId": "M1000245001F4",
                    "orderNo": "3023022014149638",
                    "sign": "LmhUnkw5j0pMiimsG6rKwdNNZGvX6GMpSmD1mdHZwq112wuK5BohmdEoqKB/jkMk28o3da4Cxh6Q+tW97+yTCemRrF+dMaHA73rpOeUuujKQl/UcFvJuMhfLBa2tp09L71NzoBqpPD6aXf37mYAz8E1HmERwFPpac5FVxIYanHG8cqmMLJYsVmHTSxWavgWU03ys9UczBePkBiR8sl2FSOhFABB0wAP28lswrV/ABS68IsLKtyd1fyI3GBfSbIK5nDEEnlE+EdElFdLs9taAxJImeVF1x4eT47+bkPJ2qS8z3K8QGzKLF3W+8SiRZGfSwDTsLKH+2Vycvy5auRl+ag=="
                  }
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/mxn/pay/query": {
      "post": {
        "summary": "MXN Disbursement Query",
        "deprecated": false,
        "description": "查询代付订单状态",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "appId": {
                    "type": "integer",
                    "description": "Business ID (obtained from the backend, must correspond to the currency in the URL)"
                  },
                  "orderId": {
                    "type": "string",
                    "description": "Merchant Order Number"
                  },
                  "orderNo": {
                    "type": "string",
                    "description": "Platform Order Number (faster response)"
                  },
                  "sign": {
                    "type": "string",
                    "description": "Signature"
                  }
                },
                "required": [
                  "appId",
                  "orderId",
                  "sign"
                ]
              },
              "example": {
                "appId": 1000,
                "orderId": "M1234567111",
                "orderNo": "3022111516571436",
                "sign": "ZxkVZL+GAyv0VhVWn4IvGYahTzxgQuthkuV2ONWiqIfIDb2avvHlFOUJVzqZi1q8CPHXZm1ltanRTRVTxfsuftLvGeDioUHglWt46/RU6c1OPznpLGsZ35Q3n5tW2y1EnOsxPynXBFLuDQy+aZ3l9u6AQ30T0zQexMGT+IxuFkmUp02g/6juaHa5ZgNMv7lN67ixIp162wrM7OJuaOif872QijSceRdZhzaMGImAwB0D4MosRV4WMBOKkwgPdmS7GuZN66YUidXk3wTGqX3MYRw6M0kj4eNegSUwPXvp4q4p0KO8Y3xUMld54GY2ApX3WN3CBtC/vpJqEszjGBbbGg=="
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "1: Normal, 0: Exception"
                    },
                    "error": {
                      "type": "string",
                      "description": "Error code"
                    },
                    "msg": {
                      "type": "string",
                      "description": "Error description"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "orderId": {
                          "type": "string",
                          "description": "Merchant Order Number (must be unique)"
                        },
                        "orderNo": {
                          "type": "string",
                          "description": "Platform Order Number"
                        },
                        "amount": {
                          "type": "string",
                          "description": "Transaction Amount"
                        },
                        "fee": {
                          "type": "string",
                          "description": "Transaction Fee"
                        },
                        "status": {
                          "type": "integer",
                          "description": "Order Status (0 Not Started, 1 Processing, 2 Success (final), 3 Failed (final), -1 Exception Pending Confirmation)",
                          "enum": [
                            0,
                            1,
                            2,
                            3,
                            -1
                          ]
                        },
                        "payTime": {
                          "type": "string",
                          "description": "Payment Success Time (available when status=2) (Mexico Time), format: yyyy-MM-dd HH:mm:ss",
                          "pattern": "^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}$"
                        },
                        "errorMsg": {
                          "type": "string",
                          "description": "Payment Failure Reason (available when status=3)"
                        },
                        "sign": {
                          "type": "string",
                          "description": "Signature"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "1": {
                    "summary": "订单失败",
                    "value": {
                      "status": "1",
                      "error": "00000000",
                      "msg": "",
                      "data": {
                        "orderId": "M1234567111",
                        "orderNo": "3022111516571436",
                        "amount": "100000.00",
                        "fee": "0.00",
                        "status": 3,
                        "errorMsg": "Đơn hàng không tồn tại",
                        "sign": "KKuvCl0SuNANJs+l2ogAaJm8pmV+Hi+Xa7q27vJ6D1Ehs4aOp13kRbITfJAhczh3T81BE9qwHeJaYwf+r0EypKM9TL6pMwfG8Az4gRy1D57wiUaVjl2PWcvbEqrn1hL0b+btkjvAM9I+CcSv+wuOW3/uku17Ws3FhgJLj9sFsQUBAPjDO+758VnwBytCOLBmljLBXyKgNgpmFQ1/DNkqWl0UNzyLK45Zw3yf5NiwhEFbvW0jlOWlfu/ql4hluISUQG573jEoFCBEnQLb2tQoRZj1QYNRCXPf5lbej0vzqbEwvR9h+ZOf255t1MocJkdIe463DTV5U3KZdVT87HMagw=="
                      }
                    }
                  },
                  "2": {
                    "summary": "订单成功",
                    "value": {
                      "status": "1",
                      "error": "00000000",
                      "msg": "",
                      "data": {
                        "orderId": "M1234567112",
                        "orderNo": "3022111517401574",
                        "amount": "100000.00",
                        "fee": "1003.00",
                        "status": 2,
                        "payTime": "2024-03-01 23:59:59",
                        "sign": "khPtOmGq+cpKX0HFAI/lbP0dx4oFyNAnL5oLsdmhDJdASlQm0yg5I3o+MhImYggEsL6c2bo5fP29t54OZFqSdQDfIuNDvGbAMAr4mRBxc0hoHLkBLyyagfVPBLyQA1JY8XV3ZL4ySzQ3ZQnMCfrh2K39ueUuz6HpZ03Hj0KYijVRCXAZaio/L5jfLBT12QXmvIfAHa8s/k9flhK05ENHPep3zjj/MZGOEaX7jkEJLfjK0duypDCa61BRQjM+oePOdVsgleIl1Yf98UAxMDZ/A3912KFHEb+/jvmdnulNbiJFyuT1fEe+j2teUgw3vFsZAtwNWAgxhC7UO+N0Q5z4EA=="
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "security": []
      }
    }
  },
  "components": {
    "schemas": {},
    "responses": {},
    "securitySchemes": {}
  },
  "servers": [
    {
      "url": "https://uat-interface.haipay.asia",
      "description": "测试-interface"
    }
  ],
  "security": []
}