{
  "openapi": "3.0.1",
  "info": {
    "title": "默认模块",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [],
  "paths": {
    "/try/collect/apply": {
      "post": {
        "summary": "土耳其里拉代收申请",
        "deprecated": false,
        "description": "创建代收订单\n\nappId需使用土耳其里拉对应的，用户支付成功后增加土耳其里拉余额",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "appId": {
                    "type": "integer",
                    "description": "业务ID（后台获取，需要根据URL中的币种传递对应的业务ID）"
                  },
                  "orderId": {
                    "type": "string",
                    "description": "商户订单号(必须保证唯一性，长度不超过48)",
                    "maxLength": 48
                  },
                  "name": {
                    "type": "string",
                    "description": "收款人姓名"
                  },
                  "phone": {
                    "type": "string",
                    "description": "真实手机号（格式参考 电话号码格式 ）"
                  },
                  "email": {
                    "type": "string",
                    "description": "真实电子邮件",
                    "format": "email"
                  },
                  "amount": {
                    "type": "string",
                    "description": "交易金额（单位：本币，精确到小数点后两位；禁止添加标点符号，例如：\",\"）",
                    "pattern": "^\\d+\\.\\d{2}$"
                  },
                  "currency": {
                    "type": "string",
                    "description": "币种(TRY)"
                  },
                  "payType": {
                    "type": "string",
                    "description": "交易类型 PAYMENT_GATEWAY"
                  },
                  "inBankCode": {
                    "type": "string",
                    "description": "支付方式"
                  },
                  "callBackUrl": {
                    "type": "string",
                    "description": "用户支付成功后跳转地址",
                    "format": "uri"
                  },
                  "callBackFailUrl": {
                    "type": "string",
                    "description": "用户支付失败后跳转地址",
                    "format": "uri"
                  },
                  "notifyUrl": {
                    "type": "string",
                    "description": "回调地址",
                    "format": "uri"
                  },
                  "subject": {
                    "type": "string",
                    "description": "支付备注"
                  },
                  "body": {
                    "type": "string",
                    "description": "备注详情"
                  },
                  "partnerUserId": {
                    "type": "string",
                    "description": "用户唯一标识（如用户ID userId），用于风控系统，必须真实有效，否则会影响交易。 格式要求：数字、大小写字母或常用符号-~!@#$%&*()_。",
                    "pattern": "^[A-Za-z0-9\\-~!@#$%&*()_]+$"
                  },
                  "sign": {
                    "type": "string",
                    "description": "签名"
                  }
                },
                "required": [
                  "appId",
                  "orderId",
                  "name",
                  "phone",
                  "email",
                  "amount",
                  "payType",
                  "inBankCode",
                  "callBackUrl",
                  "callBackFailUrl",
                  "partnerUserId",
                  "sign"
                ]
              },
              "example": {
                "appId": 1054,
                "orderId": "M233323000059",
                "amount": "300",
                "phone": "09230219312",
                "email": "23423@qq.com",
                "name": "test",
                "inBankCode": "GPay",
                "payType": "PAYMENT_GATEWAY",
                "partnerUserId": "149597870",
                "sign": "af0gAHkUOyYHu9owQp8NJ4mPEeUW4vuJcjdxqLIzrVw8AvpLSjD1DXupReSG/CyuSkFRyiIvCp5u703AuGGmfgD2gKDH3Ywau41bAbG2jnHJ8mtjiSJ5iWUzanyd4Kr7d1+rETbzUl7/BkW3t0X8UUFdqpxwG8DPUjAwUKfplWDHV7koG51Ozexd80DCsmW6eWdouAZ1uNXGLYmV3ftE3BmfNRtuv1C5bfTJWrTEIOxbF6g2uYOFZTlIgrQgd7/2PsAYwQQXNz8Q8CYl4OxqCv4pXJxaLWPbR5tqZu9og5kn32C9aHW/NlU1y39vzz+4ef81yPAqUV9oHlSMSPrMmw=="
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "状态码"
                    },
                    "error": {
                      "type": "string",
                      "description": "错误码"
                    },
                    "msg": {
                      "type": "string",
                      "description": "消息"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "orderId": {
                          "type": "string",
                          "description": "商户订单号(必须保证唯一性)"
                        },
                        "orderNo": {
                          "type": "string",
                          "description": "平台订单号"
                        },
                        "payUrl": {
                          "type": "string",
                          "description": "支付链接"
                        },
                        "sign": {
                          "type": "string",
                          "description": "签名"
                        }
                      }
                    }
                  }
                },
                "example": {
                  "status": "1",
                  "error": "00000000",
                  "msg": "",
                  "data": {
                    "orderId": "M233323000059",
                    "orderNo": "6023071013539074",
                    "payUrl": "",
                    "sign": "YEoA8Y2JzQFGVzwJSqmemm1Kfv/bfyIfCqv2dp7RNzT5B72AQvdD+nt2nR4sL1HWscvmNHyVt5ovAi7MMhy3ziih/sMph+wPx4YjH3W1h5DyBvSlWvaKfKrK5ViomZ0pPYWydwRHnnRnicxToHK9S6qtSy7Q73O0hdz4hJ9p41Th3ycBl2Q9SeqSZYSY1ohcPDhdyRf2y0prb8rHgpBKzxZ5BKX/1bsE9OmsSEHAEYT8OGgko6aNe8XPAhr4G48cpWTftvnGQuzh0O65nuZRI/PF+Axt2zJCVbFHDDSREI9NlAT82ebDqhlVdxQzKE67D1nxgjb3dPmDUYHOBpmwxQ=="
                  }
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/try/collect/query": {
      "post": {
        "summary": "土耳其里拉代收查询",
        "deprecated": false,
        "description": "创建代收订单\n当“payType=BANK_TRANSFER” 时同步返回orderNo可以直接查询\n其他支付方式异步通知后，通过orderNo查询二次确认状态",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "appId": {
                    "type": "integer",
                    "description": "业务ID（后台获取，需要根据URL中的币种传递对应的业务ID）"
                  },
                  "orderId": {
                    "type": "string",
                    "description": "商户订单号"
                  },
                  "orderNo": {
                    "type": "string",
                    "description": "平台订单号（响应快）"
                  },
                  "sign": {
                    "type": "string",
                    "description": "签名"
                  }
                },
                "required": [
                  "appId",
                  "orderId",
                  "sign"
                ]
              },
              "example": {
                "appId": 1054,
                "orderId": "M22222000028",
                "sign": "EmyJGm3ELzG4FsOd0Krs9ncbSjo4oTGuXWML+7djYla3+VAwd9wS17z38p/7U2ZAjroO04XrE7YXcB1o76Dtyipj3h3bJzs7FYma1QNkMUdt9hh7m8U6hMsMQX7vIWHtXNwz4pbTSC75+kQWXaCew7KoE6LXECdJU8AISgNgeki2TK9R0pCfshr0Z2SZBPeuT6OvIH5LdmqgdZhuqnffGU2qnXk4KMkO848e6/WALLBR+LE1wyKHfPnYVcuKSMVYxkvKyyIL5JIPEgW0o5bh4RCbaUn3NZtyYwrU1uQ3ZDFRThm9j6XAQP+LBlmq3nOePqBtp/VDVarRaV+7FbQg3A=="
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "响应状态码"
                    },
                    "error": {
                      "type": "string",
                      "description": "错误码"
                    },
                    "msg": {
                      "type": "string",
                      "description": "响应消息"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "orderId": {
                          "type": "string",
                          "description": "商户订单号(必须保证唯一性)"
                        },
                        "orderNo": {
                          "type": "string",
                          "description": "平台订单号"
                        },
                        "amount": {
                          "type": "string",
                          "description": "交易金额"
                        },
                        "actualAmount": {
                          "type": "string",
                          "description": "收到金额"
                        },
                        "fee": {
                          "type": "string",
                          "description": "手续费"
                        },
                        "status": {
                          "type": "integer",
                          "description": "状态(0未开始,1收款中,2收款成功,3收款失败,-1异常待确认)",
                          "enum": [
                            0,
                            1,
                            2,
                            3,
                            -1
                          ]
                        },
                        "payTime": {
                          "type": "string",
                          "description": "支付成功时间（当status=2时有值）, 格式: yyyy-MM-dd HH:mm:ss",
                          "pattern": "^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}$"
                        },
                        "errorMsg": {
                          "type": "string",
                          "description": "支付失败原因（当status=3时有值）"
                        },
                        "sign": {
                          "type": "string",
                          "description": "签名"
                        }
                      }
                    }
                  }
                },
                "example": {
                  "status": "1",
                  "error": "00000000",
                  "msg": "",
                  "data": {
                    "orderId": "M22222000028",
                    "orderNo": "6023042811314347",
                    "amount": "50.00",
                    "actualAmount": "0.00",
                    "fee": "0.00",
                    "status": 1,
                    "sign": "fP433ygWVDLVGxYkVnIJj7riGq0U3vyVX+MbBAImxfGLZkZcEAHVEoVYuULZSmXAAXKRSyd67WlDNm+24pougM54ofAoH4HMtCL2tfCoBReFyz3z02AGKkrKE2xWhSpWoqfQoBvzwuN5iGMMu0s9Q1YvqiwJ8WDVIENnmiIyD8qDJN7caHTW2US14/faG+69AvnuIgJ/nu7/jogOlgEYdZdVYU7gcRDE+d47KjlFGswQkJ/h/uzV7cWtUqrtOO7ZnZ3/z33Xx8awokX36QoYcPSWAU0h+Ij9O9402HNhm1eTbYcLU0uI/z8xCAtyAI/tTyiFijpiNlxUKQj+zKsILw=="
                  }
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/try/pay/apply": {
      "post": {
        "summary": "土耳其里拉代付申请",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "appId": {
                    "type": "integer",
                    "description": "业务ID（后台获取，需要根据URL中的币种传递对应的业务ID）"
                  },
                  "orderId": {
                    "type": "string",
                    "description": "商户订单号(必须保证唯一性，长度不超过48)",
                    "maxLength": 48
                  },
                  "amount": {
                    "type": "string",
                    "description": "交易金额（单位：本币）"
                  },
                  "accountType": {
                    "type": "string",
                    "description": "账户类型： BANK_ACCOUNT,EWALLET"
                  },
                  "bankCode": {
                    "type": "string",
                    "description": "银行编码"
                  },
                  "identifyType": {
                    "type": "string",
                    "description": "bankCode为PAPARA时必填 : PAPARA_NUMBER(Papara Id), PHONE(注册Papara的真实手机号), EMAIL(注册Papara的邮箱), TURKISH_ID(注册Papara的身份证号)"
                  },
                  "accountNo": {
                    "type": "string",
                    "description": "用户账号(BANK_ACCOUNT为iban)"
                  },
                  "name": {
                    "type": "string",
                    "description": "收款人姓名"
                  },
                  "phone": {
                    "type": "string",
                    "description": "真实手机号"
                  },
                  "email": {
                    "type": "string",
                    "description": "真实电子邮件"
                  },
                  "notifyUrl": {
                    "type": "string",
                    "description": "回调地址"
                  },
                  "subject": {
                    "type": "string",
                    "description": "支付备注（交易标题，商品名称，支付原因）"
                  },
                  "body": {
                    "type": "string",
                    "description": "备注详情"
                  },
                  "partnerUserId": {
                    "type": "string",
                    "description": "用户唯一标识（如用户ID userId），用于风控系统，必须真实有效，否则会影响交易。 格式要求：数字、大小写字母或常用符号-~!@#$%&*()_。"
                  },
                  "sign": {
                    "type": "string",
                    "description": "签名"
                  }
                },
                "required": [
                  "appId",
                  "orderId",
                  "amount",
                  "accountType",
                  "bankCode",
                  "accountNo",
                  "name",
                  "phone",
                  "email",
                  "partnerUserId",
                  "sign"
                ]
              },
              "example": {
                "appId": 1054,
                "orderId": "M100000450012",
                "amount": "500",
                "accountType": "BANK_ACCOUNT",
                "bankCode": "BDO",
                "accountNo": "09876543210",
                "ibanAccount": "09876543210",
                "name": "john doe",
                "phone": "09876543210",
                "email": "johndoe@cashfree.com",
                "subject": "iphone13",
                "body": "ProMotion technology with adaptive refresh rates up to 120Hz",
                "partnerUserId": "149597870",
                "sign": "I1PeK3eJOVsFFNowxVRqMXpeWm1lr/BcRpBi8WsW4wVo1+5CC3JsrFq/m/L2O69NzKHvtDWi4zia3DL3dPut0yMyUyqL91LNCSaeISbGsQPlhEsQpyTOryS/RKOfsrn2Xo37SCF/phAvndOk2jwwGwqM5xLz1ms9Ukl85wv27QFNrXIMxK2p18oe7MpMYrgf+xvEBE/VqCtKMtN9pO449wWwXzHWNPbZ76s4pAvKwRE9yXQDr7Iw14Dktcnl1FoLM4gWM/obkO+mz6SyAGDuXhVh/+OD/IGNiCyTCNq6ciQY28UnCFV6ZIP40gxsFhfBJKbK+Raw7y1Bh912ifYfug=="
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "状态码"
                    },
                    "error": {
                      "type": "string",
                      "description": "错误码"
                    },
                    "msg": {
                      "type": "string",
                      "description": "返回信息"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "orderId": {
                          "type": "string",
                          "description": "商户订单号(必须保证唯一性)"
                        },
                        "orderNo": {
                          "type": "string",
                          "description": "平台订单号"
                        },
                        "sign": {
                          "type": "string",
                          "description": "签名"
                        }
                      }
                    }
                  }
                },
                "example": {
                  "status": "1",
                  "error": "00000000",
                  "msg": "",
                  "data": {
                    "orderId": "M100000450013",
                    "orderNo": "3023062014149637",
                    "sign": "LmhUnkw5j0pMiimsG8rKwdNNZGvXH5MpSmD6mdHZwq1SQwuK5BohmdEoqKB/jkMk28o3da4Cxh6Q+tW97+yTCemRrF+dMaHA73rpOeUuujKQl/UcFvJuMhfLBa2tp09L71NzoBqpPD6aXf37mYAz8E1HmERwFPpac5FVxIYanHG8cqmMLJYsVmHTSxWavgWU03ys9UczBePkBiR8sl2FSOhFABB0wAP28lswrV/ABS68IsLKtyd1fyI3GBfSbIK5nDEEnlE+EdElFdLs9taAxJImeVF1x4eT47+bkPJ2qS8z3K8QGzKLF3W+8SiRZGfSwDTsLKH+2Vycvy5auRl+ag=="
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/try/pay/query": {
      "post": {
        "summary": "土耳其里拉代付查询",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "appId": {
                    "type": "integer",
                    "description": "业务ID（后台获取，需要根据URL中的币种传递对应的业务ID）"
                  },
                  "orderId": {
                    "type": "string",
                    "description": "商户订单号"
                  },
                  "orderNo": {
                    "type": "string",
                    "description": "平台订单号（响应快）"
                  },
                  "sign": {
                    "type": "string",
                    "description": "签名"
                  }
                },
                "required": [
                  "appId",
                  "orderId",
                  "sign"
                ]
              },
              "example": {
                "appId": 1000,
                "orderId": "M1234567111",
                "orderNo": "3022111516571436",
                "sign": "ZxkVZL+GAyv0VhvWn4IvuYahTzxgQuthkuV2ONWiqIfIDb2avvHlFOUJVzqZi1q8CPHXZm1ltanRTRVTxfsuftLvGeDioUHglWt46/RU6c1OPznpLGsZ35Q3n5tW2y1EnOsxPynXBFLuDQy+aZ3l9u6AQ30T0zQexMGT+IxuFkmUp02g/6juaHa5ZgNMv7lN67ixIp162wrM7OJuaOif872QijSceRdZhzaMGImAwB0D4MosRV4WMBOKkwgPdmS7GuZN66YUidXk3wTGqX3MYRw6M0kj4eNegSUwPXvp4q4p0KO8Y3xUMld54GY2ApX3WN3CBtC/vpJqEszjGBbbGg=="
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "响应状态码"
                    },
                    "error": {
                      "type": "string",
                      "description": "错误码"
                    },
                    "msg": {
                      "type": "string",
                      "description": "消息"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "orderId": {
                          "type": "string",
                          "description": "商户订单号(必须保证唯一性)"
                        },
                        "orderNo": {
                          "type": "string",
                          "description": "平台订单号"
                        },
                        "amount": {
                          "type": "string",
                          "description": "交易金额"
                        },
                        "fee": {
                          "type": "string",
                          "description": "手续费"
                        },
                        "status": {
                          "type": "integer",
                          "description": "订单状态(0未开始, 1放款中 2放款成功（终态） 3放款失败（终态） -1异常待确认)"
                        },
                        "payTime": {
                          "type": "string",
                          "description": "支付成功时间（当status=2时有值）, 格式: yyyy-MM-dd HH:mm:ss"
                        },
                        "errorMsg": {
                          "type": "string",
                          "description": "支付失败原因（当status=3时有值）"
                        },
                        "sign": {
                          "type": "string",
                          "description": "签名"
                        }
                      },
                      "additionalProperties": false
                    }
                  },
                  "additionalProperties": false
                },
                "examples": {
                  "1": {
                    "summary": "失败",
                    "value": {
                      "status": "1",
                      "error": "00000000",
                      "msg": "",
                      "data": {
                        "orderId": "M1234567111",
                        "orderNo": "3022111516571436",
                        "amount": "100000.00",
                        "fee": "0.00",
                        "status": 3,
                        "errorMsg": "Đơn hàng không tồn tại",
                        "sign": "KKuvCl0SuNANJs+l2ogDaJm8pmV+Hi+Xa7q27vJ6D1Ehs4aOp13kRbITfJAhczh3T81BE9qwHeJaYwf+r0EypKM9TL6pMwfG8Az4gRy1D57wiUaVjl2PWcvbEqrn1hL0b+btkjvAM9I+CcSv+wuOW3/uku17Ws3FhgJLj9sFsQUBAPjDO+758VnwBytCOLBmljLBXyKgNgpmFQ1/DNkqWl0UNzyLK45Zw3yf5NiwhEFbvW0jlOWlfu/ql4hluISUQG573jEoFCBEnQLb2tQoRZj1QYNRCXPf5lbej0vzqbEwvR9h+ZOf255t1MocJkdIe463DTV5U3KZdVT87HMagw=="
                      }
                    }
                  },
                  "2": {
                    "summary": "订单成功",
                    "value": {
                      "status": "1",
                      "error": "00000000",
                      "msg": "",
                      "data": {
                        "orderId": "M1234567112",
                        "orderNo": "3022111517401574",
                        "amount": "100000.00",
                        "fee": "1003.00",
                        "status": 2,
                        "payTime": "2024-03-01 23:59:59",
                        "sign": "khPtOmGq+cpKX0HFAI/lbP0dx4oVyNAnL5oLsdmhDJdASlQm0yg5I3o+MhImYggEsL6c2bo5fP29t54OZFqSdQDfIuNDvGbAMAr4mRBxc0hoHLkBLyyagfVPBLyQA1JY8XV3ZL4ySzQ3ZQnMCfrh2K39ueUuz6HpZ03Hj0KYijVRCXAZaio/L5jfLBT12QXmvIfAHa8s/k9flhK05ENHPep3zjj/MZGOEaX7jkEJLfjK0duypDCa61BRQjM+oePOdVsgleIl1Yf98UAxMDZ/A3912KFHEb+/jvmdnulNbiJFyuT1fEe+j2teUgw3vFsZAtwNWAgxhC7UO+N0Q5z4EA=="
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "security": []
      }
    }
  },
  "components": {
    "schemas": {},
    "responses": {},
    "securitySchemes": {}
  },
  "servers": [
    {
      "url": "https://uat-interface.haipay.asia",
      "description": "测试-interface"
    }
  ],
  "security": []
}