{
  "openapi": "3.0.1",
  "info": {
    "title": "默认模块",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [],
  "paths": {
    "/subscription/apply": {
      "post": {
        "summary": "Subscription Application",
        "deprecated": false,
        "description": "创建订阅订单",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "appId": {
                    "type": "integer",
                    "description": "Business ID (obtained from the backend, must pass the corresponding business ID according to the currency in the URL)"
                  },
                  "subscriptionOrderId": {
                    "type": "string",
                    "description": "Merchant order ID (must be unique, max length 48)",
                    "maxLength": 48
                  },
                  "amount": {
                    "type": "string",
                    "description": "Transaction amount (accurate to two decimals; punctuation such as “,” is not allowed)",
                    "pattern": "^\\d+\\.\\d{2}$"
                  },
                  "name": {
                    "type": "string",
                    "description": "User name, recommended to use real name. Format: includes firstName and lastName, separated by space. Example: Donald John Trump"
                  },
                  "phone": {
                    "type": "string",
                    "description": "Real phone number"
                  },
                  "email": {
                    "type": "string",
                    "description": "Real email",
                    "format": "email"
                  },
                  "subject": {
                    "type": "string",
                    "description": "Subscription title"
                  },
                  "body": {
                    "type": "string",
                    "description": "Remark details"
                  },
                  "inBankCode": {
                    "type": "string",
                    "description": "CREDIT_CARD, GOOGLE_PAY, APPLE_PAY",
                    "enum": [
                      "CREDIT_CARD",
                      "GOOGLE_PAY",
                      "APPLE_PAY"
                    ]
                  },
                  "payType": {
                    "type": "string",
                    "description": "SUBSCRIPTION",
                    "enum": [
                      "SUBSCRIPTION"
                    ]
                  },
                  "callBackUrl": {
                    "type": "string",
                    "description": "Redirect URL after successful payment",
                    "format": "uri"
                  },
                  "notifyUrl": {
                    "type": "string",
                    "description": "Asynchronous notification URL",
                    "format": "uri"
                  },
                  "country": {
                    "type": "string",
                    "description": "Country"
                  },
                  "currency": {
                    "type": "string",
                    "description": "Currency, currently supported: USD",
                    "enum": [
                      "USD"
                    ]
                  },
                  "partnerUserId": {
                    "type": "string",
                    "description": "User unique identifier (e.g., userId). Used for risk control. Must be real and valid, otherwise it will affect the transaction. Format: digits, letters, or common symbols -~!@#$%&*()_.",
                    "pattern": "^[A-Za-z0-9\\-~!@#$%&*()_]+$"
                  },
                  "recurringInterval": {
                    "type": "string",
                    "description": "Recurring cycle type D（day）,W（week）,M（month）,Y（year）",
                    "enum": [
                      "D",
                      "W",
                      "M",
                      "Y"
                    ]
                  },
                  "recurringIntervalCount": {
                    "type": "integer",
                    "description": "Recurring cycle interval",
                    "minimum": 1
                  },
                  "recurringMaxNumber": {
                    "type": "integer",
                    "description": "Maximum number of cycles. Regardless of cycle type, maximum duration cannot exceed 3 years. Subscription will be automatically canceled at expiration.",
                    "minimum": 1
                  },
                  "website": {
                    "type": "string",
                    "description": "Transaction website",
                    "format": "uri"
                  },
                  "retryTimes": {
                    "type": "integer",
                    "description": "Retry attempts for failed periodic deductions, default 3",
                    "minimum": 0,
                    "default": 3
                  },
                  "cancelUrl": {
                    "type": "string",
                    "description": "If provided, the user can click “Back” on the payment page to return to this URL.",
                    "format": "uri"
                  },
                  "couponPeriod": {
                    "type": "integer",
                    "description": "Discount Period (Currently only the first period discount and the full period discount are supported, i.e., couponPeriod can only be equal to 1 or recurringMaxNumber)"
                  },
                  "couponAmountPerPeriod": {
                    "type": "string",
                    "description": "Discount amount per period",
                    "pattern": "^\\d+\\.\\d{2}$"
                  },
                  "sign": {
                    "type": "string",
                    "description": "Signature"
                  }
                },
                "required": [
                  "appId",
                  "subscriptionOrderId",
                  "amount",
                  "name",
                  "phone",
                  "email",
                  "subject",
                  "inBankCode",
                  "payType",
                  "callBackUrl",
                  "notifyUrl",
                  "country",
                  "currency",
                  "partnerUserId",
                  "recurringInterval",
                  "recurringIntervalCount",
                  "recurringMaxNumber",
                  "website",
                  "retryTimes",
                  "sign"
                ],
                "additionalProperties": false
              },
              "example": {
                "country": "USA",
                "referer": "https://test.com",
                "amount": "0.5",
                "callBackUrl": "https://www.google.com",
                "inBankCode": "CREDIT_CARD",
                "subject": "Test subscription",
                "subscriptionOrderId": "1736739758574",
                "recurringIntervalCount": 1,
                "sign": "JeJR4N40eKncoohebUN31aNqPqpBxR799rmMutqrSmMaBn0Sjmqbskl4Wiitmatvvx6tqvuwkOYtk6ryrYj7YqJxDeNfDqthWzOxv2ixkKY0YDoWEAra9sWc4CnXBBssP0VIKg0jSTMNzdvmvuNBa7sLEQj5YjgswUnCGtYCmsz154JHSSRpdeYDLL+Nt5b96pzQn8WyRr6b/9SSCrLCWSdt22gJmY5sQh7cc9OcJfAGb5E1XflTq5Va78cV+fw9hHhaZmFzKncg4wxrdaatxg9tCElMJpL1OuWO7XLfcfqgA/8Y/qRCWmNf11Ji3ZSrr7rU4+V7Egrfu1Fcr5DTlw==",
                "partnerUserId": "H20241231",
                "payType": "SUBSCRIPTION",
                "phone": "0845632145871",
                "appId": 1724,
                "name": "howard",
                "notifyUrl": "https://www.google.com",
                "currency": "USD",
                "email": "howard@gmail.com",
                "recurringInterval": "D"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "1: Normal, 0: Exception"
                    },
                    "error": {
                      "type": "string",
                      "description": "Error code"
                    },
                    "msg": {
                      "type": "string",
                      "description": "Error description"
                    },
                    "data": {
                      "type": "object",
                      "description": "",
                      "properties": {
                        "subscriptionOrderId": {
                          "type": "string",
                          "description": "Merchant subscription ID (must be unique)"
                        },
                        "subscriptionNo": {
                          "type": "string",
                          "description": "Platform subscription ID"
                        },
                        "appId": {
                          "type": "string",
                          "description": "Business ID"
                        },
                        "subject": {
                          "type": "string",
                          "description": "Payment note"
                        },
                        "payType": {
                          "type": "string",
                          "description": "Subscription fixed as SUBSCRIPTION"
                        },
                        "inBankCode": {
                          "type": "string",
                          "description": "Bank code"
                        },
                        "amount": {
                          "type": "string",
                          "description": "Deduction amount"
                        },
                        "payUrl": {
                          "type": "string",
                          "description": "Authorization URL"
                        },
                        "recurringInterval": {
                          "type": "string",
                          "description": "Recurring cycle W, M, Y",
                          "enum": [
                            "W",
                            "M",
                            "Y"
                          ]
                        },
                        "recurringIntervalCount": {
                          "type": "string",
                          "description": "Recurring cycle interval"
                        },
                        "status": {
                          "type": "string",
                          "description": "1: Normal, 0: Exception",
                          "enum": [
                            "-1",
                            "1",
                            "2",
                            "3",
                            "4"
                          ]
                        },
                        "clientToken": {
                          "type": "string",
                          "description": "Client token used in the JavaScript Web SDK (see [HaiPaySDK.js](#haipaysdk))"
                        },
                        "sign": {
                          "type": "string",
                          "description": "Signature"
                        }
                      }
                    }
                  },
                  "additionalProperties": false
                },
                "example": {
                  "status": "1",
                  "error": "00000000",
                  "msg": "",
                  "data": {
                    "subscriptionNo": "4025011311423010028",
                    "subscriptionOrderId": "1736739758574",
                    "appId": 1724,
                    "subject": "Test subscription",
                    "payType": "SUBSCRIPTION",
                    "inBankCode": "CREDIT_CARD",
                    "amount": 0.5,
                    "recurringInterval": "D",
                    "recurringIntervalCount": 1,
                    "status": "2",
                    "sign": "QrOo7yPJMTRk92bP9WU8P0ATdRvCm8dWElhbxqV6qmZEWZDRXeJAwUvd3839zErg+3tN/U4Rwyru219AkXg9CJZtocna3fiYj7uLxwD6bpAp+i9DGz5ZKV9ab5mwIEPWIQXKuY6wATzmlz6W4TvAkRqgGtqLkwYUaeqsmgJrh4WlIMK13GW/zvoCmYfFD6pNZUByVixpll8JPeZG7F9d+x7yjDigJZ2S1wm4F307OzZJkUSKSvQn6Q0lOvp1JS0feXSC+hwCfrdllFXIE10TDV0itoPY5G7+3QdmHpINWp3kWmepR/1pOsN+09hLxe8xKAIZrX2GFHY00xo3QnxBIw=="
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/subscription/query": {
      "post": {
        "summary": "Subscription Query",
        "deprecated": false,
        "description": "查询订阅订单",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "appId": {
                    "type": "integer",
                    "description": "Business ID (obtained from the backend, must pass the corresponding business ID according to the currency in the URL)"
                  },
                  "subscriptionNo": {
                    "type": "string",
                    "description": "Platform subscription ID"
                  },
                  "sign": {
                    "type": "string",
                    "description": "Signature"
                  }
                },
                "required": [
                  "appId",
                  "subscriptionNo",
                  "sign"
                ],
                "additionalProperties": false
              },
              "example": {
                "appId": 1724,
                "sign": "gETp00ngwiG0qPVcpldPGEsWRCShOJUbwxWizbL9xGbWCtlBsTPFshQtClLtBCRAdhoVNZAD7UQXjdiAsr74neYu1akj1a6d3sNapGaqoTdBgykXyr1hLVe14AIUhLRg0Mj2elOlMPiWMdccSC+i4G/lfPpJLpS/T08S8qttExTOjML5Rrny5jNsYedjf+Jo3jrPsLcfZFX3QrWA4txPG+x7ZrShXUonOiZMoH6hwU8PcETrC0vpGqTwySJ6siS2AwyPOZElR6nf3geIx7GAllFUuZSyjCvRDE+9JeZl5Y2Ohlm9xcRxqHgMi4YB3jSJcwo7GqGqnPapZnO2GvcbGw==",
                "subscriptionNo": "4025011311423010028"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "1: Normal, 0: Exception"
                    },
                    "error": {
                      "type": "string",
                      "description": "Error code"
                    },
                    "msg": {
                      "type": "string",
                      "description": "Error description"
                    },
                    "data": {
                      "type": "object",
                      "description": "",
                      "properties": {
                        "subscriptionOrderId": {
                          "type": "string",
                          "description": "Merchant subscription ID (must be unique)"
                        },
                        "subscriptionNo": {
                          "type": "string",
                          "description": "Platform subscription ID"
                        },
                        "appId": {
                          "type": "string",
                          "description": "Business ID"
                        },
                        "subject": {
                          "type": "string",
                          "description": "Payment note"
                        },
                        "currency": {
                          "type": "string",
                          "description": "Currency"
                        },
                        "payType": {
                          "type": "string",
                          "description": "Subscription fixed as SUBSCRIPTION"
                        },
                        "inBankCode": {
                          "type": "string",
                          "description": "Bank code"
                        },
                        "amount": {
                          "type": "string",
                          "description": "Deduction amount"
                        },
                        "recurringInterval": {
                          "type": "string",
                          "description": "Recurring cycle W, M, Y"
                        },
                        "recurringIntervalCount": {
                          "type": "string",
                          "description": "Recurring cycle interval"
                        },
                        "status": {
                          "type": "string",
                          "description": "1: Normal, 0: Exception"
                        },
                        "deductList": {
                          "type": "array",
                          "description": "Deduction list",
                          "items": {
                            "type": "object",
                            "properties": {
                              "deductNo": {
                                "type": "string",
                                "description": "Subscription deduction ID"
                              },
                              "amount": {
                                "type": "string",
                                "description": "Deduction amount"
                              },
                              "status": {
                                "type": "integer",
                                "description": "1: Normal, 0: Exception"
                              },
                              "orderNo": {
                                "type": "string",
                                "description": "Platform order ID"
                              },
                              "startTime": {
                                "type": "string",
                                "description": "Subscription deduction cycle - start time"
                              },
                              "endTime": {
                                "type": "string",
                                "description": "Subscription deduction cycle - end time"
                              }
                            },
                            "required": [
                              "deductNo",
                              "amount",
                              "status",
                              "orderNo",
                              "startTime",
                              "endTime"
                            ]
                          }
                        },
                        "sign": {
                          "type": "string",
                          "description": "Signature"
                        }
                      }
                    }
                  },
                  "example": {
                    "status": "1",
                    "error": "00000000",
                    "msg": "",
                    "data": {
                      "subscriptionOrderId": "1736739758574",
                      "subscriptionNo": "4025011311423010028",
                      "appId": 1724,
                      "subject": "Test subscription",
                      "payType": "SUBSCRIPTION",
                      "inBankCode": "CREDIT_CARD",
                      "amount": 0.5,
                      "recurringInterval": "D",
                      "recurringIntervalCount": 1,
                      "status": "2",
                      "deductList": [
                        {
                          "deductNo": "4125011311423010028",
                          "amount": "0.99",
                          "status": 2,
                          "orderNo": "2025011311423010028",
                          "startTime": "2024-12-18 09:25:11",
                          "endTime": "2024-12-25 09:25:11"
                        }
                      ],
                      "sign": "fscM1XiVPqDb/NxrZuVv33zvqFxsXsKri6+MzIsWqdMlcsa7E3ayGNHg6ChiVxFVdow3NAlmg4szGXp0AtvOLDdQ/BAfC8DWpbktjDXeiEQ7ma1/ZKsmVrrLHzF01B5UI33xYX+qMsjMQ/yJBHwY1LTOhPq3lIwShwhB92CCd6IfPPkSi1EPDL6QLKAll3NNRVUw3vktIx+ghePojrmkgOesD7ujCPlXPjvznJ4o99BFhwPr6i+a0w++ZvfoE/NuClTCP4mf1n4umnw70GqHDv3OfwVk9FeE27SC/TMJIgVJiVc9L3o+mJNUyaIT3o9EyKkfUl+lNsz1KnUyfjycUg=="
                    }
                  }
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/subscription/cancel": {
      "post": {
        "summary": "Subscription Cancel",
        "deprecated": false,
        "description": "取消订阅",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "appId": {
                    "type": "integer",
                    "description": "Business ID (obtained from the backend, must pass the corresponding business ID according to the currency in the URL)"
                  },
                  "subscriptionNo": {
                    "type": "string",
                    "description": "Platform subscription ID"
                  },
                  "sign": {
                    "type": "string",
                    "description": "Signature"
                  }
                },
                "required": [
                  "appId",
                  "subscriptionNo",
                  "sign"
                ],
                "additionalProperties": false
              },
              "example": {
                "appId": 1724,
                "sign": "gETp00ngwiG0qPVcpldPGEsWRCShOJUbwxWizbL9xGbWCtlBsTPFshQtClLtBCRAdhoVNZAD7UQXjdiAsr74neYu1akj1a6d3sNapGaqoTdBgykXyr1hLVe14AIUhLRg0Mj2elOlMPiWMdccSC+i4G/lfPpJLpS/T08S8qttExTOjML5Rrny5jNsYedjf+Jo3jrPsLcfZFX3QrWA4txPG+x7ZrShXUonOiZMoH6hwU8PcETrC0vpGqTwySJ6siS2AwyPOZElR6nf3geIx7GAllFUuZSyjCvRDE+9JeZl5Y2Ohlm9xcRxqHgMi4YB3jSJcwo7GqGqnPapZnO2GvcbGw==",
                "subscriptionNo": "4025011311423010028"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "1: Normal, 0: Exception",
                      "example": "1"
                    },
                    "error": {
                      "type": "string",
                      "description": "Error code",
                      "example": "00000000"
                    },
                    "msg": {
                      "type": "string",
                      "description": "Error description",
                      "example": ""
                    },
                    "data": {
                      "type": "object",
                      "description": "",
                      "properties": {
                        "subscriptionOrderId": {
                          "type": "string",
                          "description": "Merchant subscription ID (must be unique)"
                        },
                        "subscriptionNo": {
                          "type": "string",
                          "description": "Platform subscription ID"
                        },
                        "appId": {
                          "type": "string",
                          "description": "Business ID"
                        },
                        "payType": {
                          "type": "string",
                          "description": "Subscription fixed as SUBSCRIPTION",
                          "example": "SUBSCRIPTION"
                        },
                        "inBankCode": {
                          "type": "string",
                          "description": "Bank code"
                        },
                        "status": {
                          "type": "string",
                          "description": "Subscription status (-1: Error, 1: Processing, 2: Success, 3: Failed, 4: Canceled)",
                          "enum": [
                            "-1",
                            "1",
                            "2",
                            "3",
                            "4"
                          ]
                        },
                        "sign": {
                          "type": "string",
                          "description": "Signature"
                        }
                      },
                      "additionalProperties": false
                    }
                  },
                  "additionalProperties": false
                },
                "example": {
                  "status": "1",
                  "error": "00000000",
                  "msg": "",
                  "data": {
                    "appId": 1724,
                    "subscriptionNo": "4025011311423010028",
                    "status": "4",
                    "payType": "SUBSCRIPTION",
                    "inBankCode": "CREDIT_CARD",
                    "sign": "lynHvI+9JhVbhwHiinJGlDEq7CVU67WkNUsNURs1wu4bI2/2ePVORGqbVdnaU+L9qV4JN35gM2hHadn4pye/Xk+iztLVSbDh5F9XpKAmLeLCcYj+II0pt4Eo4QPxnYJjmMzbDu6fdWgjgi/go2M75N7Fqv2QgV/tIu1O2pe4/LRPe3l/IODvW+ppvbf5FHk5hO2AaLUX/Fn7H0MIv6kcKAhu7ImBrNpF79VPj9YC1qXghJE11q4aHx7xfDDCn4GiqDJBXbzLtqGP6cS2CVXlyLxGziKDxM1+Bv02XNbjzYKwcaS1VDNfmzlglVH+GHZcgVpiEa3u4ffezu2NN2B4Yg=="
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/subscription/refund/apply": {
      "post": {
        "summary": "Subscription Refund",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "appId": {
                    "type": "integer",
                    "description": "Business ID (obtained from the backend, must pass the corresponding business ID according to the currency in the URL)"
                  },
                  "subscriptionNo": {
                    "type": "string",
                    "description": "Platform subscription ID"
                  },
                  "orderNo": {
                    "type": "string",
                    "description": "Platform order ID"
                  },
                  "sign": {
                    "type": "string",
                    "description": "Signature"
                  }
                },
                "required": [
                  "appId",
                  "subscriptionNo",
                  "orderNo",
                  "sign"
                ],
                "additionalProperties": false
              },
              "example": {
                "appId": 1091,
                "subscriptionNo": "4025050711174217272",
                "orderNo": "2025050711174213012",
                "sign": "Zs9W0md9b+z5zdswnr5ItJio+TU8xzXe/2CXjEUY7bA9y56fECE54xtPIq70agEChhc/b06OtHHASojuYW55TmTAeFIgQMBT5hrlC+m5jf845OBs2KmG+RRODn3hwp6bjTnnkg37mueRvs+1pXEU7DbucYmlRrRmyOywpf+t3RHjU+5qrnK9Bw6RDwT5LtfhHIMCYQA3mLhHlJkSN5oQq1j5F0xQjy51A8Gp6e1Sp2ZeHDr1SsPsh8K7XN2kxDyenpDhhFRU2tZkIYRJFYyrwFfUsCtg7t6V8dzwHDGrU8EuCC1CGcmn/sQ1FYk0V3FnVmiL5FW1eBPgWdahtxWolg=="
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "1: Normal, 0: Exception",
                      "default": "1"
                    },
                    "error": {
                      "type": "string",
                      "description": "Error code",
                      "default": "00000000"
                    },
                    "msg": {
                      "type": "string",
                      "description": "Error description",
                      "default": ""
                    },
                    "data": {
                      "type": "object",
                      "description": "",
                      "properties": {
                        "orderNo": {
                          "type": "string",
                          "description": "Platform order ID"
                        },
                        "subscriptionNo": {
                          "type": "string",
                          "description": "Platform subscription ID"
                        },
                        "appId": {
                          "type": "string",
                          "description": "Business ID"
                        },
                        "refundNo": {
                          "type": "string",
                          "description": "Refund order ID"
                        },
                        "sign": {
                          "type": "string",
                          "description": "Signature"
                        }
                      },
                      "default": {}
                    }
                  }
                },
                "example": {
                  "status": "1",
                  "error": "00000000",
                  "msg": "",
                  "data": {
                    "appId": 1091,
                    "subscriptionNo": "4025050711174217272",
                    "orderNo": "2025050711174213012",
                    "refundNo": "2525050711193210376",
                    "sign": "fseIFahsO8jttM7T3hNnmJiLmEBr4mRlcM/two4SeODZ262+T3nnymNEVMRyvQwDRp9OULBrQlD7ZQI6T9M7ub0qni3bjv/cF1cY/LE4VGhR3rrAnBr30JFBQlcpLzqtxrPokgdhUoP5P5lbhSCnBl9s5mVFIhGDeJArZ76rG1LfoFgw3osZdk5D6GcdIjNYOn1QvucK2TZeJiEVxGk0fwAJMGTxknqBRU1XttX1OPILHs8U1sF5RL7aDG5N1Oarxd6CiLCvyHE242RKgvdN9GYiVjXNHjoO+M1VmxFFlMzryEA7d2d0cHygf0PjuaiOiKDQ98Kyy7fmj1VuA4WiHg=="
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    }
  },
  "components": {
    "schemas": {},
    "responses": {},
    "securitySchemes": {}
  },
  "servers": [
    {
      "url": "https://uat-interface.haipay.asia",
      "description": "测试-interface"
    }
  ],
  "security": []
}